version: '3'

services:
    redis:
        image: redis:7
        ports:
            - 6379:6379
        networks:
            - poll-tier
            - back-tier
        restart: on-failure

    poll:
        build: ./poll
        ports:
            - 5000:80
        networks:
            - poll-tier
        environment:
            - REDIS_HOST=redis
        restart: on-failure
        depends_on:
            - redis

    worker:
        build: ./worker
        networks:
            - back-tier
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_DB=poll_db
            - POSTGRES_USER=poll_user
            - POSTGRES_PASSWORD=poll_password
        restart: on-failure
        depends_on:
            - db
            - redis

    db:
        image: postgres:16
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=poll_db
            - POSTGRES_USER=poll_user
            - POSTGRES_PASSWORD=poll_password
        networks:
            - result-tier
            - back-tier
        restart: on-failure

    result:
        build: ./result
        ports:
            - 5001:80
        networks:
            - result-tier
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_DB=poll_db
            - POSTGRES_USER=poll_user
            - POSTGRES_PASSWORD=poll_password
        restart: on-failure
        depends_on:
            - db

volumes:
    db-data:
networks:
    poll-tier:
    result-tier:
    back-tier: